### ISSUE TITLE
License

### ISSUE THREAD

**Issue by portela** [SKisContent/django-excel-fixture#1]
Hi,

I like your project 'django-excel-fixture' and think it has potential.

I really would like to test it, and, maybe even improve it; but your code has no license with it (which means it is not open-source). Using a code without a license is a huge liability for people and corporations. You can read more about it at https://choosealicense.com/licenses/mit/.

So, I kindly ask you to add an open-source, and permissive, license to you. May I suggest a MIT LICENSE (https://choosealicense.com/licenses/mit/)?

Sincerely,

**Comment by SKisContent** [comment]
Sure, it's done. Thanks for your interest.

SK

**Comment by portela** [comment]
Thank you!!!

I think it willbe very helpfull!!!
